version: "3.9"
services:
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mixpreparados_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shivah
    ports:
      - "5432:5432"

volumes:
  postgres_data:
