version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default  # <-- Agregado

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    working_dir: /code
    env_file:
      - .env
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`elcompadremix.com`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web.middlewares=redirect-to-https@file
      - traefik.http.routers.websecure.rule=Host(`elcompadremix.com`)
      - traefik.http.routers.websecure.entrypoints=websecure
      - traefik.http.routers.websecure.tls.certresolver=letsencrypt
      - traefik.http.services.web.loadbalancer.server.port=8000

networks:
  default:
    driver: bridge
