version: "3.8"

services:
  web:
    build: .
    command: bash -c "
      until nc -z db 5432; do echo '⏳ Esperando a DB...'; sleep 1; done;
      echo '✅ DB lista';
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8005"
    volumes:
      - .:/code
    working_dir: /code
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.elcompadremix.rule=Host(`elcompadremix.com`)
      - traefik.http.routers.elcompadremix.entrypoints=web
      - traefik.http.routers.elcompadremixsecure.rule=Host(`elcompadremix.com`)
      - traefik.http.routers.elcompadremixsecure.entrypoints=websecure
      - traefik.http.routers.elcompadremixsecure.tls.certresolver=letsencrypt
      - traefik.http.services.elcompadremix.loadbalancer.server.port=8005

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge