# Generated by Django 5.1.6 on 2025-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto del cliente'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Calificación (1 a 5)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='comment',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
