# Generated by Django 5.1.7 on 2025-03-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Descripción pendiente'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='Descripción pendiente'),
            preserve_default=False,
        ),
    ]
